### ISSUE TITLE
correlation must be greater than 0 or less than 1

### ISSUE THREAD

**Issue by HeatherUrry** [Lakens/ANOVApower#11]
Hello! 

Great package. I have a matrix of correlations that includes negative values, but receive this error message: "Correlation must be greater than 0 and less than 1." Can you fix to allow negative values please?

Heather

**Comment by Lakens** [comment]
Can you confirm upon reinstalling the package this is now fixed? It was an incorrect error message - should obviously have allowed negative correlations.
