### ISSUE TITLE
run time

### ISSUE THREAD

**Issue by HeatherUrry** [Lakens/ANOVApower#13]
Hello! 

I'm running ANOVA_power with 1,000 sims for a design_result that is a 3b*2w*7w design with n = 500. The cor_mat is 42 x 42. It's been running for about 22 hours and counting. Is this expected or should I assume there's a problem and quit it? I could obviously choose fewer nsims for the purpose of testing, but even nsims = 10 didn't finish within a couple of minutes. I'd be happy to upload the design_result object if you're curious or need it to think about the question. Thanks!

Heather

**Comment by Lakens** [comment]
Please email us directly. This is not an issue with the package. It just takes a long time to do huge designs. We can think of how to improve this but in principle it works. Email us the code. We can take a look.
