### ISSUE TITLE
Accepts negative SD

### ISSUE THREAD

**Issue by debruine** [Lakens/ANOVApower#6]
`ANOVA_power` shouldn't accept SD < 0 (and should probably warn users if SD == 0)

**Comment by arcaldwell49** [comment]
Alright, I've created an error message for the ANOVA_design function to prevent SD <=0
`#Ensure sd is greater than 0
  if (any(sd <= 0)) {
    stop("Standard deviation (sd) is less than or equal to zero; input a value greater than zero")
  }`
